building block workflow

diff --git a/.github/Workflows/01-building-blocks.yaml b/.github/Workflows/01-building-blocks.yaml
--- a/.github/Workflows/01-building-blocks.yaml
+++ b/.github/Workflows/01-building-blocks.yaml
@@ -1,5 +1,5 @@
 name: 01 - Building blocks
-push: on
+on: workflow_dispatch
 
 jobs:
   echo-hello:
@@ -12,8 +12,8 @@ jobs:
     steps:
       - name: say-goodbye
         run: echo "Goodbye & thanks ....welcome to Github Actions Master"
-    steps: 
-      - name: failing step
-        run: |
-        echo "This steps is failing, please check if its gets failed"
-        exit 1
+    # steps: 
+    #   - name: failing step
+    #     run: |
+    #     echo "This steps is failing, please check if its gets failed"
+    #     exit 1
